### ISSUE TITLE
go get mosn.io/proxy-wasm-go-host/proxywasm/common is failing

### ISSUE THREAD

**Issue by sanfern** [mosn/proxy-wasm-go-host#12]
I am trying to use this module in my proxy code, while I am running go get I get the following error -
#go get mosn.io/proxy-wasm-go-host/proxywasm/common    
#go get: module mosn.io/proxy-wasm-go-host@upgrade found (v0.1.0), but does not contain package mosn.io/proxy-wasm-go-host/proxywasm/common

**Comment by taoyuanyuan** [comment]
have a try
`go get mosn.io/proxy-wasm-go-host`

**Comment by sanfern** [comment]
We have tried this and works, we are not able to get the latest changes. if you can release the latest version may resolve this issue.

**Comment by taoyuanyuan** [comment]
@antJack  cc

**Comment by antJack** [comment]
try this command to get the latest commit

> go get mosn.io/proxy-wasm-go-host@3fb13ba

but if you depend on the package: mosn.io/mosn, then you may fail since it requires a non-latest version of go-host
