### ISSUE TITLE
Drop ABI v0.1.0

### ISSUE THREAD

**Issue by codefromthecrypt** [mosn/proxy-wasm-go-host#22]
Per #10 the current code doesn't properly implement v0.1.0, and worse that version isn't really used or maintained anymore. I suggest focusing effort on maintained ABI. Notably this should also drop "wasi_unstable" for "wasi_snapshot_preview1" as that's what's in use by current compilers.

Until this is dropped implementing another host impl is too much low value work, as it is porting for unused and unmaintable ABI.

@taoyuanyuan @antJack FYI I'm pausing efforts until this is done as I am way over budget already and there's no value proceeding if we have to support an incorrect implementation of an unused ABI version.

**Comment by antJack** [comment]
it's better to let both v0.1.0 and v2 coexist, since we still have internal usage of v0.1.0, and can still build up v0.1.0's wasm file, ref: https://github.com/mosn/proxy-wasm-go-host/issues/23.  
we also welcome to update the example and the recommended version to v2, ref: https://github.com/mosn/proxy-wasm-go-host/issues/23

**Comment by codefromthecrypt** [comment]
v2 here is incompatible with normal v2 so it is really not worth doing. For example, people using current SDKs will fail in a very hard to troubleshoot way. I learned this after opening this issue.

**Comment by codefromthecrypt** [comment]
I think the best approach is to let this repo die and create a compatible implementation directly in mosn/mosn. that way current users can stay taken care of even if they are using revlocked sdks. once they migrate, this repo can be archived.

**Comment by antJack** [comment]
As I mentioned in https://github.com/mosn/proxy-wasm-go-host/issues/10, there is no documenta'tion

**Comment by codefromthecrypt** [comment]
I don't disagree about lack of documentation. however, it is hurting mosn to intentionally not be compatible with current SDKs. For example, you can't upgrade tinygo and the version in use is highly flawed.

Another choice is to stop using proxy-wasm, because it is incompatible with other proxy-wasm.. since that's the case it is suspicious why use it at all.

**Comment by codefromthecrypt** [comment]
things have changed a lot since #10 also, even if the spec is still very poor. The ecosystem make more tests to deal with this, since mosn is also go it can benefit from it. 

https://github.com/tetratelabs/proxy-wasm-go-sdk/releases/tag/v0.20.0

Anyway it is your choice, but I think this isn't proxy-wasm anymore it is a dialect of it, and version locked with tooling no-one else can use. I'll close this issue though as it is clear this repository must stay how it is for the foreseeable future.

**Comment by antJack** [comment]
the lack of documentation is an important problem, any update on v2 ABI just goes on sdk codes, and we do not have so much time to keep follow with the latest code.

**Comment by codefromthecrypt** [comment]
the documentation problem of proxy-wasm will never change, imho. waiting for that is like waiting for the sun to turn blue.  I don't really care, just I was hopeful to be able to help show a nice go server technology able to do well. I can't do it here because you have some constraints that don't match reality.

1. cannot stop incompatible 1.0
2. cannot change 2.0 to be compatible

so, I have nothing I can offer. In any case I don't really like proxy-wasm personally anyway. I just wanted to help show a better proxy story in go 🤷

**Comment by antJack** [comment]
Maybe a bit of a misunderstanding, it's free to make 2.0 compatible with current sdk, we welcome pr.

**Comment by codefromthecrypt** [comment]
ok I have run out of time and working in this codebase is still costly due to the way it is structured and not tested. don't wait for me. It would be much faster to start over.
